version: '3.5'
services:
  groupe3:
    image: chocoboco/SimpleChat
    networks:
      #network pour traefik
      - 'traefik-public'
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
      restart_policy:
        max_attempts: 5
      labels:
        - traefik.frontend.rule=Host:frontend.simplechat.fun
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
    ports:
      - 8080:8080
      - 8082:8082
      - 8081:8081
      - 8001:8001
    depends_on:
      - traefik


networks:
  traefik-public:
    external: true