name: Notification on push

on:
  push:
    branches:
      - develop
      - frontend
      - BDD
      - apiMessages

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: SimpleBot
          DISCORD_AVATAR: https://i.chzbgr.com/full/8334924288/hCFACD046/stock-photo-of-hide-the-pain-harold-looking-at-the-camera-with-a-pained-expression
        uses: Ilshidur/action-discord@master
        with:
          args: 'Nouveau commit sur SimpleChat'
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master